import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import React from 'react'
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet'
import Script from 'next/script'
import dynamic from 'next/dynamic'
const inter = Inter({ subsets: ['latin'] })
const MyMap = dynamic(() => import('../components/map'), { ssr: false })


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <MyMap />


      </main>

    </>
  )
}

